import datetime
import hug


# @hug.get(examples="name=Jhon Doe&amp;age=30")
# @hug.local()
# def say_hello(name: hug.types.text, age: hug.types.number, hug_timer=3):
#     """Decimos hola al usuario y calculamos su año de nacimiento"""
#     year_of_birth = datetime.datetime.now().year - age
#     return {
#         'message': "Hola {0}, naciste el año {1}".format(name, year_of_birth),
#         'took': float(hug_timer)
#     }


# if __name__ == '__main__':
#     print(say_hello("Gabriel", 23))

class Comuna(object):
    def __init__(self, nombre, cut):
        self.nombre = nombre
        self.cut = cut

def myFunc(e):
  return e['nombre']

@hug.get()
def comunasApi():
    comunas = [
        {"nombre": "Arica", "cut": 15101},
        {"nombre": "Camarones", "cut": 15102},
        {"nombre": "Putre", "cut": 15201},
        {"nombre": "General Lagos", "cut": 15202},
        {"nombre": "Iquique", "cut":1101},
        {"nombre": "Alto Hospicio", "cut":1107},
        {"nombre": "Pozo Almonte", "cut":1401},
        {"nombre": "Camiña", "cut":1402},
        {"nombre": "Colchane", "cut":1403},
        {"nombre": "Huara", "cut":1404},
        {"nombre": "Pica", "cut":1405},
        {"nombre": "Antofagasta", "cut":2101},
        {"nombre": "Mejillones", "cut":2102},
        {"nombre": "Sierra Gorda", "cut":2103},
        {"nombre": "Taltal", "cut":2104},
        {"nombre": "Calama", "cut":2201},
        {"nombre": "Ollagüe", "cut":2202},
        {"nombre": "San Pedro de Atacama", "cut":2203},
        {"nombre": "Tocopilla", "cut":2301},
        {"nombre": "María Elena", "cut":2302},
        {"nombre": "Copiapó", "cut":3101},
        {"nombre": "Caldera", "cut":3102},
        {"nombre": "Tierra Amarilla", "cut":3103},
        {"nombre": "Chañaral", "cut":3201},
        {"nombre": "Diego de Almagro", "cut":3202},
        {"nombre": "Vallenar", "cut":3301},
        {"nombre": "Alto del Carmen", "cut":3302},
        {"nombre": "Freirina", "cut":3303},
        {"nombre": "Huasco", "cut":3304},
        {"nombre": "La Serena", "cut":4101},
        {"nombre": "Coquimbo", "cut":4102},
        {"nombre": "Andacollo", "cut":4103},
        {"nombre": "La Higuera", "cut":4104},
        {"nombre": "Paihuano", "cut":4105},
        {"nombre": "Vicuña", "cut":4106},
        {"nombre": "Illapel", "cut":4201},
        {"nombre": "Canela", "cut":4202},
        {"nombre": "Los Vilos", "cut":4203},
        {"nombre": "Salamanca", "cut":4204},
        {"nombre": "Ovalle", "cut":4301},
        {"nombre": "Combarbalá", "cut":4302},
        {"nombre": "Monte Patria", "cut":4303},
        {"nombre": "Punitaqui", "cut":4304},
        {"nombre": "Río Hurtado", "cut":4305},
        {"nombre": "Valparaíso", "cut":5101},
        {"nombre": "Casablanca", "cut":5102},
        {"nombre": "Concón", "cut":5103},
        {"nombre": "Juan Fernández", "cut":5104},
        {"nombre": "Puchuncaví", "cut":5105},
        {"nombre": "Quintero", "cut":5107},
        {"nombre": "Viña del Mar", "cut":5109},
        {"nombre": "Isla de Pascua", "cut":5201},
        {"nombre": "Los Andes", "cut":5301},
        {"nombre": "Calle Larga", "cut":5302},
        {"nombre": "Rinconada", "cut":5303},
        {"nombre": "San Esteban", "cut":5304},
        {"nombre": "La Ligua", "cut":5401},
        {"nombre": "Cabildo", "cut":5402},
        {"nombre": "Papudo", "cut":5403},
        {"nombre": "Petorca", "cut":5404},
        {"nombre": "Zapallar", "cut":5405},
        {"nombre": "Quillota", "cut":5501},
        {"nombre": "La Calera", "cut":5502},
        {"nombre": "Hijuelas", "cut":5503},
        {"nombre": "La Cruz", "cut":5504},
        {"nombre": "Nogales", "cut":5506},
        {"nombre": "San Antonio", "cut":5601},
        {"nombre": "Algarrobo", "cut":5602},
        {"nombre": "Cartagena", "cut":5603},
        {"nombre": "El Quisco", "cut":5604},
        {"nombre": "El Tabo", "cut":5605},
        {"nombre": "Santo Domingo", "cut":5606},
        {"nombre": "San Felipe", "cut":5701},
        {"nombre": "Catemu", "cut":5702},
        {"nombre": "Llay-Llay", "cut":5703},
        {"nombre": "Panquehue", "cut":5704},
        {"nombre": "Putaendo", "cut":5705},
        {"nombre": "Santa María", "cut":5706},
        {"nombre": "Quilpué", "cut":5801},
        {"nombre": "Limache", "cut":5802},
        {"nombre": "Olmué", "cut":5803},
        {"nombre": "Villa Alemana", "cut":5804},
        {"nombre": "Rancagua", "cut":6101},
        {"nombre": "Codegua", "cut":6102},
        {"nombre": "Coinco", "cut":6103},
        {"nombre": "Coltauco", "cut":6104},
        {"nombre": "Doñihue", "cut":6105},
        {"nombre": "Graneros", "cut":6106},
        {"nombre": "Las Cabras", "cut":6107},
        {"nombre": "Machalí", "cut":6108},
        {"nombre": "Malloa", "cut":6109},
        {"nombre": "Mostazal", "cut":6110},
        {"nombre": "Olivar", "cut":6111},
        {"nombre": "Peumo", "cut":6112},
        {"nombre": "Pichidegua", "cut":6113},
        {"nombre": "Quinta de Tilcoco", "cut":6114},
        {"nombre": "Rengo", "cut":6115},
        {"nombre": "Requínoa", "cut":6116},
        {"nombre": "San Vicente", "cut":6117},
        {"nombre": "Pichilemu", "cut":6201},
        {"nombre": "La Estrella", "cut":6202},
        {"nombre": "Litueche", "cut":6203},
        {"nombre": "Marchihue", "cut":6204},
        {"nombre": "Navidad", "cut":6205},
        {"nombre": "Paredones", "cut":6206},
        {"nombre": "San Fernando", "cut":6301},
        {"nombre": "Chépica", "cut":6302},
        {"nombre": "Chimbarongo", "cut":6303},
        {"nombre": "Lolol", "cut":6304},
        {"nombre": "Nancagua", "cut":6305},
        {"nombre": "Palmilla", "cut":6306},
        {"nombre": "Peralillo", "cut":6307},
        {"nombre": "Placilla", "cut":6308},
        {"nombre": "Pumanque", "cut":6309},
        {"nombre": "Santa Cruz", "cut":6310},
        {"nombre": "Talca", "cut":7101},
        {"nombre": "Constitución", "cut":7102},
        {"nombre": "Curepto", "cut":7103},
        {"nombre": "Empedrado", "cut":7104},
        {"nombre": "Maule", "cut":7105},
        {"nombre": "Pelarco", "cut":7106},
        {"nombre": "Pencahue", "cut":7107},
        {"nombre": "Río Claro", "cut":7108},
        {"nombre": "San Clemente", "cut":7109},
        {"nombre": "San Rafael", "cut":7110},
        {"nombre": "Cauquenes", "cut":7201},
        {"nombre": "Chanco", "cut":7202},
        {"nombre": "Pelluhue", "cut":7203},
        {"nombre": "Curicó", "cut":7301},
        {"nombre": "Hualañé", "cut":7302},
        {"nombre": "Licantén", "cut":7303},
        {"nombre": "Molina", "cut":7304},
        {"nombre": "Rauco", "cut":7305},
        {"nombre": "Romeral", "cut":7306},
        {"nombre": "Sagrada Familia", "cut":7307},
        {"nombre": "Teno", "cut":7308},
        {"nombre": "Vichuquén", "cut":7309},
        {"nombre": "Linares", "cut":7401},
        {"nombre": "Colbún", "cut":7402},
        {"nombre": "Longaví", "cut":7403},
        {"nombre": "Parral", "cut":7404},
        {"nombre": "Retiro", "cut":7405},
        {"nombre": "San Javier", "cut":7406},
        {"nombre": "Villa Alegre", "cut":7407},
        {"nombre": "Yerbas Buenas", "cut":7408},
        {"nombre": "Chillán", "cut": 16101},
        {"nombre": "Bulnes", "cut": 16102},
        {"nombre": "Chillán Viejo", "cut": 16103},
        {"nombre": "El Carmen", "cut": 16104},
        {"nombre": "Pemuco", "cut": 16105},
        {"nombre": "Pinto", "cut": 16106},
        {"nombre": "Quillón", "cut": 16107},
        {"nombre": "San Ignacio", "cut": 16108},
        {"nombre": "Yungay", "cut": 16109},
        {"nombre": "Quirihue", "cut": 16201},
        {"nombre": "Cobquecura", "cut": 16202},
        {"nombre": "Coelemu", "cut": 16203},
        {"nombre": "Ninhue", "cut": 16204},
        {"nombre": "Portezuelo", "cut": 16205},
        {"nombre": "Ránquil", "cut": 16206},
        {"nombre": "Treguaco", "cut": 16207},
        {"nombre": "San Carlos", "cut": 16301},
        {"nombre": "Coihueco", "cut": 16302},
        {"nombre": "Ñiquén", "cut": 16303},
        {"nombre": "San Fabián", "cut": 16304},
        {"nombre": "San Nicolás", "cut": 16305},
        {"nombre": "Concepción", "cut":8101},
        {"nombre": "Coronel", "cut":8102},
        {"nombre": "Chiguayante", "cut":8103},
        {"nombre": "Florida", "cut":8104},
        {"nombre": "Hualqui", "cut":8105},
        {"nombre": "Lota", "cut":8106},
        {"nombre": "Penco", "cut":8107},
        {"nombre": "San Pedro de La Paz", "cut":8108},
        {"nombre": "Santa Juana", "cut":8109},
        {"nombre": "Talcahuano", "cut":8110},
        {"nombre": "Tomé", "cut":8111},
        {"nombre": "Hualpén", "cut":8112},
        {"nombre": "Lebu", "cut":8201},
        {"nombre": "Arauco", "cut":8202},
        {"nombre": "Cañete", "cut":8203},
        {"nombre": "Contulmo", "cut":8204},
        {"nombre": "Curanilahue", "cut":8205},
        {"nombre": "Los Álamos", "cut":8206},
        {"nombre": "Tirúa", "cut":8207},
        {"nombre": "Los Ángeles", "cut":8301},
        {"nombre": "Antuco", "cut":8302},
        {"nombre": "Cabrero", "cut":8303},
        {"nombre": "Laja", "cut":8304},
        {"nombre": "Mulchén", "cut":8305},
        {"nombre": "Nacimiento", "cut":8306},
        {"nombre": "Negrete", "cut":8307},
        {"nombre": "Quilaco", "cut":8308},
        {"nombre": "Quilleco", "cut":8309},
        {"nombre": "San Rosendo", "cut":8310},
        {"nombre": "Santa Bárbara", "cut":8311},
        {"nombre": "Tucapel", "cut":8312},
        {"nombre": "Yumbel", "cut":8313},
        {"nombre": "Alto Biobío", "cut":8314},
        {"nombre": "Temuco", "cut":9101},
        {"nombre": "Carahue", "cut":9102},
        {"nombre": "Cunco", "cut":9103},
        {"nombre": "Curarrehue", "cut":9104},
        {"nombre": "Freire", "cut":9105},
        {"nombre": "Galvarino", "cut":9106},
        {"nombre": "Gorbea", "cut":9107},
        {"nombre": "Lautaro", "cut":9108},
        {"nombre": "Loncoche", "cut":9109},
        {"nombre": "Melipeuco", "cut":9110},
        {"nombre": "Nueva Imperial", "cut":9111},
        {"nombre": "Padre Las Casas", "cut":9112},
        {"nombre": "Perquenco", "cut":9113},
        {"nombre": "Pitrufquén", "cut":9114},
        {"nombre": "Pucón", "cut":9115},
        {"nombre": "Saavedra", "cut":9116},
        {"nombre": "Teodoro Schmidt", "cut":9117},
        {"nombre": "Toltén", "cut":9118},
        {"nombre": "Vilcún", "cut":9119},
        {"nombre": "Villarrica", "cut":9120},
        {"nombre": "Cholchol", "cut":9121},
        {"nombre": "Angol", "cut":9201},
        {"nombre": "Collipulli", "cut":9202},
        {"nombre": "Curacautín", "cut":9203},
        {"nombre": "Ercilla", "cut":9204},
        {"nombre": "Lonquimay", "cut":9205},
        {"nombre": "Los Sauces", "cut":9206},
        {"nombre": "Lumaco", "cut":9207},
        {"nombre": "Purén", "cut":9208},
        {"nombre": "Renaico", "cut":9209},
        {"nombre": "Traiguén", "cut":9210},
        {"nombre": "Victoria", "cut":9211},
        {"nombre": "Valdivia", "cut": 14101},
        {"nombre": "Corral", "cut": 14102},
        {"nombre": "Lanco", "cut": 14103},
        {"nombre": "Los Lagos", "cut": 14104},
        {"nombre": "Máfil", "cut": 14105},
        {"nombre": "Mariquina", "cut": 14106},
        {"nombre": "Paillaco", "cut": 14107},
        {"nombre": "Panguipulli", "cut": 14108},
        {"nombre": "La Unión", "cut": 14201},
        {"nombre": "Futrono", "cut": 14202},
        {"nombre": "Lago Ranco", "cut": 14203},
        {"nombre": "Río Bueno", "cut": 14204},
        {"nombre": "Puerto Montt", "cut": 10101},
        {"nombre": "Calbuco", "cut": 10102},
        {"nombre": "Cochamó", "cut": 10103},
        {"nombre": "Fresia", "cut": 10104},
        {"nombre": "Frutillar", "cut": 10105},
        {"nombre": "Los Muermos", "cut": 10106},
        {"nombre": "Llanquihue", "cut": 10107},
        {"nombre": "Maullín", "cut": 10108},
        {"nombre": "Puerto Varas", "cut": 10109},
        {"nombre": "Castro", "cut": 10201},
        {"nombre": "Ancud", "cut": 10202},
        {"nombre": "Chonchi", "cut": 10203},
        {"nombre": "Curaco de Vélez", "cut": 10204},
        {"nombre": "Dalcahue", "cut": 10205},
        {"nombre": "Puqueldón", "cut": 10206},
        {"nombre": "Queilén", "cut": 10207},
        {"nombre": "Quellón", "cut": 10208},
        {"nombre": "Quemchi", "cut": 10209},
        {"nombre": "Quinchao", "cut": 10210},
        {"nombre": "Osorno", "cut": 10301},
        {"nombre": "Puerto Octay", "cut": 10302},
        {"nombre": "Purranque", "cut": 10303},
        {"nombre": "Puyehue", "cut": 10304},
        {"nombre": "Río Negro", "cut": 10305},
        {"nombre": "San Juan de la Costa", "cut": 10306},
        {"nombre": "San Pablo", "cut": 10307},
        {"nombre": "Chaitén", "cut": 10401},
        {"nombre": "Futaleufú", "cut": 10402},
        {"nombre": "Hualaihué", "cut": 10403},
        {"nombre": "Palena", "cut": 10404},
        {"nombre": "Coyhaique", "cut": 11101},
        {"nombre": "Lago Verde", "cut": 11102},
        {"nombre": "Aysén", "cut": 11201},
        {"nombre": "Cisnes", "cut": 11202},
        {"nombre": "Guaitecas", "cut": 11203},
        {"nombre": "Cochrane", "cut": 11301},
        {"nombre": "O'Higgins", "cut": 11302},
        {"nombre": "Tortel", "cut": 11303},
        {"nombre": "Chile Chico", "cut": 11401},
        {"nombre": "Río Ibáñez", "cut": 11402},
        {"nombre": "Punta Arenas", "cut": 12101},
        {"nombre": "Laguna Blanca", "cut": 12102},
        {"nombre": "Río Verde", "cut": 12103},
        {"nombre": "San Gregorio", "cut": 12104},
        {"nombre": "Cabo de Hornos", "cut": 12201},
        {"nombre": "Antártica", "cut": 12202},
        {"nombre": "Porvenir", "cut": 12301},
        {"nombre": "Primavera", "cut": 12302},
        {"nombre": "Timaukel", "cut": 12303},
        {"nombre": "Natales", "cut": 12401},
        {"nombre": "Torres del Paine", "cut": 12402},
        {"nombre": "Santiago", "cut": 13101},
        {"nombre": "Cerrillos", "cut": 13102},
        {"nombre": "Cerro Navia", "cut": 13103},
        {"nombre": "Conchalí", "cut": 13104},
        {"nombre": "El Bosque", "cut": 13105},
        {"nombre": "Estación Central", "cut": 13106},
        {"nombre": "Huechuraba", "cut": 13107},
        {"nombre": "Independencia", "cut": 13108},
        {"nombre": "La Cisterna", "cut": 13109},
        {"nombre": "La Florida", "cut": 13110},
        {"nombre": "La Granja", "cut": 13111},
        {"nombre": "La Pintana", "cut": 13112},
        {"nombre": "La Reina", "cut": 13113},
        {"nombre": "Las Condes", "cut": 13114},
        {"nombre": "Lo Barnechea", "cut": 13115},
        {"nombre": "Lo Espejo", "cut": 13116},
        {"nombre": "Lo Prado", "cut": 13117},
        {"nombre": "Macul", "cut": 13118},
        {"nombre": "Maipú", "cut": 13119},
        {"nombre": "Ñuñoa", "cut": 13120},
        {"nombre": "Pedro Aguirre Cerda", "cut": 13121},
        {"nombre": "Peñalolén", "cut": 13122},
        {"nombre": "Providencia", "cut": 13123},
        {"nombre": "Pudahuel", "cut": 13124},
        {"nombre": "Quilicura", "cut": 13125},
        {"nombre": "Quinta Normal", "cut": 13126},
        {"nombre": "Recoleta", "cut": 13127},
        {"nombre": "Renca", "cut": 13128},
        {"nombre": "San Joaquín", "cut": 13129},
        {"nombre": "San Miguel", "cut": 13130},
        {"nombre": "San Ramón", "cut": 13131},
        {"nombre": "Vitacura", "cut": 13132},
        {"nombre": "Puente Alto", "cut": 13201},
        {"nombre": "Pirque", "cut": 13202},
        {"nombre": "San José de Maipo", "cut": 13203},
        {"nombre": "Colina", "cut": 13301},
        {"nombre": "Lampa", "cut": 13302},
        {"nombre": "Til Til", "cut": 13303},
        {"nombre": "San Bernardo", "cut": 13401},
        {"nombre": "Buin", "cut": 13402},
        {"nombre": "Calera de Tango", "cut": 13403},
        {"nombre": "Paine", "cut": 13404},
        {"nombre": "Melipilla", "cut": 13501},
        {"nombre": "Alhué", "cut": 13502},
        {"nombre": "Curacaví", "cut": 13503},
        {"nombre": "María Pinto", "cut": 13504},
        {"nombre": "San Pedro", "cut": 13505},
        {"nombre": "Talagante", "cut": 13601},
        {"nombre": "El Monte", "cut": 13602},
        {"nombre": "Isla de Maipo", "cut": 13603},
        {"nombre": "Padre Hurtado", "cut": 13604},
        {"nombre": "Peñaflor", "cut": 13605}
    ]
    comunas.sort(key=myFunc)
    return comunas


if __name__ == '__main__':
    print(comunasApi())
