import hug

# for(var i=0;i<rows.length;i++){
# var cut = rows[i].getElementsByTagName("td")[0];
# var nombre = rows[i].getElementsByTagName("td")[1];
# var provincia = rows[i].getElementsByTagName("td")[3];
# var region = rows[i].getElementsByTagName("td")[4];
# let experiment = {cut}
# let experiment2 = {nombre}
# let experiment3 = {provincia}
# let experiment4 = {region}
# console.log('{"nombre":"'+experiment2.nombre.innerText+'", "cut":'+experiment.cut.innerText+', "provincia":"'+experiment3.provincia.innerText+'", "región":"'+experiment4.region.innerText+'"},')
# }

class Comuna(object):
    def __init__(self, nombre, cut):
        self.nombre = nombre
        self.cut = cut


def nombreComuna(comuna):
    return comuna['nombre']


@hug.get()
def comunasApi():
    comunas = [
        {"nombre": "Arica", "cut": 15101, "provincia": "Arica",
            "región": "Arica y Parinacota"},
        {"nombre": "Camarones", "cut": 15102,
            "provincia": "Arica", "región": "Arica y Parinacota"},
        {"nombre": "Putre", "cut": 15201, "provincia": "Parinacota",
            "región": "Arica y Parinacota"},
        {"nombre": "General Lagos", "cut": 15202,
            "provincia": "Parinacota", "región": "Arica y Parinacota"},
        {"nombre": "Iquique", "cut": 1101,
            "provincia": "Iquique", "región": "Tarapacá"},
        {"nombre": "Alto Hospicio", "cut": 1107,
            "provincia": "Iquique", "región": "Tarapacá"},
        {"nombre": "Pozo Almonte", "cut": 1401,
            "provincia": "Tamarugal", "región": "Tarapacá"},
        {"nombre": "Camiña", "cut": 1402,
            "provincia": "Tamarugal", "región": "Tarapacá"},
        {"nombre": "Colchane", "cut": 1403,
            "provincia": "Tamarugal", "región": "Tarapacá"},
        {"nombre": "Huara", "cut": 1404,
            "provincia": "Tamarugal", "región": "Tarapacá"},
        {"nombre": "Pica", "cut": 1405,
            "provincia": "Tamarugal", "región": "Tarapacá"},
        {"nombre": "Antofagasta", "cut": 2101,
            "provincia": "Antofagasta", "región": "Antofagasta"},
        {"nombre": "Mejillones", "cut": 2102,
            "provincia": "Antofagasta", "región": "Antofagasta"},
        {"nombre": "Sierra Gorda", "cut": 2103,
            "provincia": "Antofagasta", "región": "Antofagasta"},
        {"nombre": "Taltal", "cut": 2104,
            "provincia": "Antofagasta", "región": "Antofagasta"},
        {"nombre": "Calama", "cut": 2201,
            "provincia": "El Loa", "región": "Antofagasta"},
        {"nombre": "Ollagüe", "cut": 2202,
            "provincia": "El Loa", "región": "Antofagasta"},
        {"nombre": "San Pedro de Atacama", "cut": 2203,
            "provincia": "El Loa", "región": "Antofagasta"},
        {"nombre": "Tocopilla", "cut": 2301,
            "provincia": "Tocopilla", "región": "Antofagasta"},
        {"nombre": "María Elena", "cut": 2302,
            "provincia": "Tocopilla", "región": "Antofagasta"},
        {"nombre": "Copiapó", "cut": 3101,
            "provincia": "Copiapó", "región": "Atacama"},
        {"nombre": "Caldera", "cut": 3102,
            "provincia": "Copiapó", "región": "Atacama"},
        {"nombre": "Tierra Amarilla", "cut": 3103,
            "provincia": "Copiapó", "región": "Atacama"},
        {"nombre": "Chañaral", "cut": 3201,
            "provincia": "Chañaral", "región": "Atacama"},
        {"nombre": "Diego de Almagro", "cut": 3202,
            "provincia": "Chañaral", "región": "Atacama"},
        {"nombre": "Vallenar", "cut": 3301,
            "provincia": "Huasco", "región": "Atacama"},
        {"nombre": "Alto del Carmen", "cut": 3302,
            "provincia": "Huasco", "región": "Atacama"},
        {"nombre": "Freirina", "cut": 3303,
            "provincia": "Huasco", "región": "Atacama"},
        {"nombre": "Huasco", "cut": 3304, "provincia": "Huasco", "región": "Atacama"},
        {"nombre": "La Serena", "cut": 4101,
            "provincia": "Elqui", "región": "Coquimbo"},
        {"nombre": "Coquimbo", "cut": 4102,
            "provincia": "Elqui", "región": "Coquimbo"},
        {"nombre": "Andacollo", "cut": 4103,
            "provincia": "Elqui", "región": "Coquimbo"},
        {"nombre": "La Higuera", "cut": 4104,
            "provincia": "Elqui", "región": "Coquimbo"},
        {"nombre": "Paihuano", "cut": 4105,
            "provincia": "Elqui", "región": "Coquimbo"},
        {"nombre": "Vicuña", "cut": 4106, "provincia": "Elqui", "región": "Coquimbo"},
        {"nombre": "Illapel", "cut": 4201,
            "provincia": "Choapa", "región": "Coquimbo"},
        {"nombre": "Canela", "cut": 4202,
            "provincia": "Choapa", "región": "Coquimbo"},
        {"nombre": "Los Vilos", "cut": 4203,
            "provincia": "Choapa", "región": "Coquimbo"},
        {"nombre": "Salamanca", "cut": 4204,
            "provincia": "Choapa", "región": "Coquimbo"},
        {"nombre": "Ovalle", "cut": 4301,
            "provincia": "Limarí", "región": "Coquimbo"},
        {"nombre": "Combarbalá", "cut": 4302,
            "provincia": "Limarí", "región": "Coquimbo"},
        {"nombre": "Monte Patria", "cut": 4303,
            "provincia": "Limarí", "región": "Coquimbo"},
        {"nombre": "Punitaqui", "cut": 4304,
            "provincia": "Limarí", "región": "Coquimbo"},
        {"nombre": "Río Hurtado", "cut": 4305,
            "provincia": "Limarí", "región": "Coquimbo"},
        {"nombre": "Valparaíso", "cut": 5101,
            "provincia": "Valparaíso", "región": "Valparaíso"},
        {"nombre": "Casablanca", "cut": 5102,
            "provincia": "Valparaíso", "región": "Valparaíso"},
        {"nombre": "Concón", "cut": 5103,
            "provincia": "Valparaíso", "región": "Valparaíso"},
        {"nombre": "Juan Fernández", "cut": 5104,
            "provincia": "Valparaíso", "región": "Valparaíso"},
        {"nombre": "Puchuncaví", "cut": 5105,
            "provincia": "Valparaíso", "región": "Valparaíso"},
        {"nombre": "Quintero", "cut": 5107,
            "provincia": "Valparaíso", "región": "Valparaíso"},
        {"nombre": "Viña del Mar", "cut": 5109,
            "provincia": "Valparaíso", "región": "Valparaíso"},
        {"nombre": "Isla de Pascua", "cut": 5201,
            "provincia": "Isla de Pascua", "región": "Valparaíso"},
        {"nombre": "Los Andes", "cut": 5301,
            "provincia": "Los Andes", "región": "Valparaíso"},
        {"nombre": "Calle Larga", "cut": 5302,
            "provincia": "Los Andes", "región": "Valparaíso"},
        {"nombre": "Rinconada", "cut": 5303,
            "provincia": "Los Andes", "región": "Valparaíso"},
        {"nombre": "San Esteban", "cut": 5304,
            "provincia": "Los Andes", "región": "Valparaíso"},
        {"nombre": "La Ligua", "cut": 5401,
            "provincia": "Petorca", "región": "Valparaíso"},
        {"nombre": "Cabildo", "cut": 5402,
            "provincia": "Petorca", "región": "Valparaíso"},
        {"nombre": "Papudo", "cut": 5403,
            "provincia": "Petorca", "región": "Valparaíso"},
        {"nombre": "Petorca", "cut": 5404,
            "provincia": "Petorca", "región": "Valparaíso"},
        {"nombre": "Zapallar", "cut": 5405,
            "provincia": "Petorca", "región": "Valparaíso"},
        {"nombre": "Quillota", "cut": 5501,
            "provincia": "Quillota", "región": "Valparaíso"},
        {"nombre": "La Calera", "cut": 5502,
            "provincia": "Quillota", "región": "Valparaíso"},
        {"nombre": "Hijuelas", "cut": 5503,
            "provincia": "Quillota", "región": "Valparaíso"},
        {"nombre": "La Cruz", "cut": 5504,
            "provincia": "Quillota", "región": "Valparaíso"},
        {"nombre": "Nogales", "cut": 5506,
            "provincia": "Quillota", "región": "Valparaíso"},
        {"nombre": "San Antonio", "cut": 5601,
            "provincia": "San Antonio", "región": "Valparaíso"},
        {"nombre": "Algarrobo", "cut": 5602,
            "provincia": "San Antonio", "región": "Valparaíso"},
        {"nombre": "Cartagena", "cut": 5603,
            "provincia": "San Antonio", "región": "Valparaíso"},
        {"nombre": "El Quisco", "cut": 5604,
            "provincia": "San Antonio", "región": "Valparaíso"},
        {"nombre": "El Tabo", "cut": 5605,
            "provincia": "San Antonio", "región": "Valparaíso"},
        {"nombre": "Santo Domingo", "cut": 5606,
            "provincia": "San Antonio", "región": "Valparaíso"},
        {"nombre": "San Felipe", "cut": 5701,
            "provincia": "San Felipe de Aconcagua", "región": "Valparaíso"},
        {"nombre": "Catemu", "cut": 5702,
            "provincia": "San Felipe de Aconcagua", "región": "Valparaíso"},
        {"nombre": "Llay-Llay", "cut": 5703,
            "provincia": "San Felipe de Aconcagua", "región": "Valparaíso"},
        {"nombre": "Panquehue", "cut": 5704,
            "provincia": "San Felipe de Aconcagua", "región": "Valparaíso"},
        {"nombre": "Putaendo", "cut": 5705,
            "provincia": "San Felipe de Aconcagua", "región": "Valparaíso"},
        {"nombre": "Santa María", "cut": 5706,
            "provincia": "San Felipe de Aconcagua", "región": "Valparaíso"},
        {"nombre": "Quilpué", "cut": 5801,
            "provincia": "Marga Marga", "región": "Valparaíso"},
        {"nombre": "Limache", "cut": 5802,
            "provincia": "Marga Marga", "región": "Valparaíso"},
        {"nombre": "Olmué", "cut": 5803,
            "provincia": "Marga Marga", "región": "Valparaíso"},
        {"nombre": "Villa Alemana", "cut": 5804,
            "provincia": "Marga Marga", "región": "Valparaíso"},
        {"nombre": "Rancagua", "cut": 6101, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Codegua", "cut": 6102, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Coinco", "cut": 6103, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Coltauco", "cut": 6104, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Doñihue", "cut": 6105, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Graneros", "cut": 6106, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Las Cabras", "cut": 6107, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Machalí", "cut": 6108, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Malloa", "cut": 6109, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Mostazal", "cut": 6110, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Olivar", "cut": 6111, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Peumo", "cut": 6112, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Pichidegua", "cut": 6113, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Quinta de Tilcoco", "cut": 6114, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Rengo", "cut": 6115, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Requínoa", "cut": 6116, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "San Vicente", "cut": 6117, "provincia": "Cachapoal",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Pichilemu", "cut": 6201, "provincia": "Cardenal Caro",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "La Estrella", "cut": 6202, "provincia": "Cardenal Caro",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Litueche", "cut": 6203, "provincia": "Cardenal Caro",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Marchihue", "cut": 6204, "provincia": "Cardenal Caro",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Navidad", "cut": 6205, "provincia": "Cardenal Caro",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Paredones", "cut": 6206, "provincia": "Cardenal Caro",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "San Fernando", "cut": 6301, "provincia": "Colchagua",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Chépica", "cut": 6302, "provincia": "Colchagua",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Chimbarongo", "cut": 6303, "provincia": "Colchagua",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Lolol", "cut": 6304, "provincia": "Colchagua",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Nancagua", "cut": 6305, "provincia": "Colchagua",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Palmilla", "cut": 6306, "provincia": "Colchagua",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Peralillo", "cut": 6307, "provincia": "Colchagua",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Placilla", "cut": 6308, "provincia": "Colchagua",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Pumanque", "cut": 6309, "provincia": "Colchagua",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Santa Cruz", "cut": 6310, "provincia": "Colchagua",
            "región": "Lib. Gral. Bernardo O'Higgins"},
        {"nombre": "Talca", "cut": 7101, "provincia": "Talca", "región": "Maule"},
        {"nombre": "Constitución", "cut": 7102,
            "provincia": "Talca", "región": "Maule"},
        {"nombre": "Curepto", "cut": 7103, "provincia": "Talca", "región": "Maule"},
        {"nombre": "Empedrado", "cut": 7104,
            "provincia": "Talca", "región": "Maule"},
        {"nombre": "Maule", "cut": 7105, "provincia": "Talca", "región": "Maule"},
        {"nombre": "Pelarco", "cut": 7106, "provincia": "Talca", "región": "Maule"},
        {"nombre": "Pencahue", "cut": 7107,
            "provincia": "Talca", "región": "Maule"},
        {"nombre": "Río Claro", "cut": 7108,
            "provincia": "Talca", "región": "Maule"},
        {"nombre": "San Clemente", "cut": 7109,
            "provincia": "Talca", "región": "Maule"},
        {"nombre": "San Rafael", "cut": 7110,
            "provincia": "Talca", "región": "Maule"},
        {"nombre": "Cauquenes", "cut": 7201,
            "provincia": "Cauquenes", "región": "Maule"},
        {"nombre": "Chanco", "cut": 7202,
            "provincia": "Cauquenes", "región": "Maule"},
        {"nombre": "Pelluhue", "cut": 7203,
            "provincia": "Cauquenes", "región": "Maule"},
        {"nombre": "Curicó", "cut": 7301, "provincia": "Curicó", "región": "Maule"},
        {"nombre": "Hualañé", "cut": 7302, "provincia": "Curicó", "región": "Maule"},
        {"nombre": "Licantén", "cut": 7303,
            "provincia": "Curicó", "región": "Maule"},
        {"nombre": "Molina", "cut": 7304, "provincia": "Curicó", "región": "Maule"},
        {"nombre": "Rauco", "cut": 7305, "provincia": "Curicó", "región": "Maule"},
        {"nombre": "Romeral", "cut": 7306, "provincia": "Curicó", "región": "Maule"},
        {"nombre": "Sagrada Familia", "cut": 7307,
            "provincia": "Curicó", "región": "Maule"},
        {"nombre": "Teno", "cut": 7308, "provincia": "Curicó", "región": "Maule"},
        {"nombre": "Vichuquén", "cut": 7309,
            "provincia": "Curicó", "región": "Maule"},
        {"nombre": "Linares", "cut": 7401,
            "provincia": "Linares", "región": "Maule"},
        {"nombre": "Colbún", "cut": 7402, "provincia": "Linares", "región": "Maule"},
        {"nombre": "Longaví", "cut": 7403,
            "provincia": "Linares", "región": "Maule"},
        {"nombre": "Parral", "cut": 7404, "provincia": "Linares", "región": "Maule"},
        {"nombre": "Retiro", "cut": 7405, "provincia": "Linares", "región": "Maule"},
        {"nombre": "San Javier", "cut": 7406,
            "provincia": "Linares", "región": "Maule"},
        {"nombre": "Villa Alegre", "cut": 7407,
            "provincia": "Linares", "región": "Maule"},
        {"nombre": "Yerbas Buenas", "cut": 7408,
            "provincia": "Linares", "región": "Maule"},
        {"nombre": "Chillán", "cut": 16101,
            "provincia": "Diguillín", "región": "Ñuble"},
        {"nombre": "Bulnes", "cut": 16102,
            "provincia": "Diguillín", "región": "Ñuble"},
        {"nombre": "Chillán Viejo", "cut": 16103,
            "provincia": "Diguillín", "región": "Ñuble"},
        {"nombre": "El Carmen", "cut": 16104,
            "provincia": "Diguillín", "región": "Ñuble"},
        {"nombre": "Pemuco", "cut": 16105,
            "provincia": "Diguillín", "región": "Ñuble"},
        {"nombre": "Pinto", "cut": 16106,
            "provincia": "Diguillín", "región": "Ñuble"},
        {"nombre": "Quillón", "cut": 16107,
            "provincia": "Diguillín", "región": "Ñuble"},
        {"nombre": "San Ignacio", "cut": 16108,
            "provincia": "Diguillín", "región": "Ñuble"},
        {"nombre": "Yungay", "cut": 16109,
            "provincia": "Diguillín", "región": "Ñuble"},
        {"nombre": "Quirihue", "cut": 16201,
            "provincia": "Itata", "región": "Ñuble"},
        {"nombre": "Cobquecura", "cut": 16202,
            "provincia": "Itata", "región": "Ñuble"},
        {"nombre": "Coelemu", "cut": 16203,
            "provincia": "Itata", "región": "Ñuble"},
        {"nombre": "Ninhue", "cut": 16204, "provincia": "Itata", "región": "Ñuble"},
        {"nombre": "Portezuelo", "cut": 16205,
            "provincia": "Itata", "región": "Ñuble"},
        {"nombre": "Ránquil", "cut": 16206,
            "provincia": "Itata", "región": "Ñuble"},
        {"nombre": "Treguaco", "cut": 16207,
            "provincia": "Itata", "región": "Ñuble"},
        {"nombre": "San Carlos", "cut": 16301,
            "provincia": "Punilla", "región": "Ñuble"},
        {"nombre": "Coihueco", "cut": 16302,
            "provincia": "Punilla", "región": "Ñuble"},
        {"nombre": "Ñiquén", "cut": 16303,
            "provincia": "Punilla", "región": "Ñuble"},
        {"nombre": "San Fabián", "cut": 16304,
            "provincia": "Punilla", "región": "Ñuble"},
        {"nombre": "San Nicolás", "cut": 16305,
            "provincia": "Punilla", "región": "Ñuble"},
        {"nombre": "Concepción", "cut": 8101,
            "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Coronel", "cut": 8102,
            "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Chiguayante", "cut": 8103,
            "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Florida", "cut": 8104,
            "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Hualqui", "cut": 8105,
            "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Lota", "cut": 8106, "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Penco", "cut": 8107,
            "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "San Pedro de La Paz", "cut": 8108,
            "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Santa Juana", "cut": 8109,
            "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Talcahuano", "cut": 8110,
            "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Tomé", "cut": 8111, "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Hualpén", "cut": 8112,
            "provincia": "Concepción", "región": "Biobío"},
        {"nombre": "Lebu", "cut": 8201, "provincia": "Arauco", "región": "Biobío"},
        {"nombre": "Arauco", "cut": 8202, "provincia": "Arauco", "región": "Biobío"},
        {"nombre": "Cañete", "cut": 8203, "provincia": "Arauco", "región": "Biobío"},
        {"nombre": "Contulmo", "cut": 8204,
            "provincia": "Arauco", "región": "Biobío"},
        {"nombre": "Curanilahue", "cut": 8205,
            "provincia": "Arauco", "región": "Biobío"},
        {"nombre": "Los Álamos", "cut": 8206,
            "provincia": "Arauco", "región": "Biobío"},
        {"nombre": "Tirúa", "cut": 8207, "provincia": "Arauco", "región": "Biobío"},
        {"nombre": "Los Ángeles", "cut": 8301,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Antuco", "cut": 8302, "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Cabrero", "cut": 8303,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Laja", "cut": 8304, "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Mulchén", "cut": 8305,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Nacimiento", "cut": 8306,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Negrete", "cut": 8307,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Quilaco", "cut": 8308,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Quilleco", "cut": 8309,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "San Rosendo", "cut": 8310,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Santa Bárbara", "cut": 8311,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Tucapel", "cut": 8312,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Yumbel", "cut": 8313, "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Alto Biobío", "cut": 8314,
            "provincia": "Biobío", "región": "Biobío"},
        {"nombre": "Temuco", "cut": 9101,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Carahue", "cut": 9102,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Cunco", "cut": 9103,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Curarrehue", "cut": 9104,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Freire", "cut": 9105,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Galvarino", "cut": 9106,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Gorbea", "cut": 9107,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Lautaro", "cut": 9108,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Loncoche", "cut": 9109,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Melipeuco", "cut": 9110,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Nueva Imperial", "cut": 9111,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Padre Las Casas", "cut": 9112,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Perquenco", "cut": 9113,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Pitrufquén", "cut": 9114,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Pucón", "cut": 9115,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Saavedra", "cut": 9116,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Teodoro Schmidt", "cut": 9117,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Toltén", "cut": 9118,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Vilcún", "cut": 9119,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Villarrica", "cut": 9120,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Cholchol", "cut": 9121,
            "provincia": "Cautín", "región": "La Araucanía"},
        {"nombre": "Angol", "cut": 9201,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Collipulli", "cut": 9202,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Curacautín", "cut": 9203,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Ercilla", "cut": 9204,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Lonquimay", "cut": 9205,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Los Sauces", "cut": 9206,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Lumaco", "cut": 9207,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Purén", "cut": 9208,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Renaico", "cut": 9209,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Traiguén", "cut": 9210,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Victoria", "cut": 9211,
            "provincia": "Malleco", "región": "La Araucanía"},
        {"nombre": "Valdivia", "cut": 14101,
            "provincia": "Valdivia", "región": "Los Ríos"},
        {"nombre": "Corral", "cut": 14102,
            "provincia": "Valdivia", "región": "Los Ríos"},
        {"nombre": "Lanco", "cut": 14103,
            "provincia": "Valdivia", "región": "Los Ríos"},
        {"nombre": "Los Lagos", "cut": 14104,
            "provincia": "Valdivia", "región": "Los Ríos"},
        {"nombre": "Máfil", "cut": 14105,
            "provincia": "Valdivia", "región": "Los Ríos"},
        {"nombre": "Mariquina", "cut": 14106,
            "provincia": "Valdivia", "región": "Los Ríos"},
        {"nombre": "Paillaco", "cut": 14107,
            "provincia": "Valdivia", "región": "Los Ríos"},
        {"nombre": "Panguipulli", "cut": 14108,
            "provincia": "Valdivia", "región": "Los Ríos"},
        {"nombre": "La Unión", "cut": 14201,
            "provincia": "Ranco", "región": "Los Ríos"},
        {"nombre": "Futrono", "cut": 14202,
            "provincia": "Ranco", "región": "Los Ríos"},
        {"nombre": "Lago Ranco", "cut": 14203,
            "provincia": "Ranco", "región": "Los Ríos"},
        {"nombre": "Río Bueno", "cut": 14204,
            "provincia": "Ranco", "región": "Los Ríos"},
        {"nombre": "Puerto Montt", "cut": 10101,
            "provincia": "Llanquihue", "región": "Los Lagos"},
        {"nombre": "Calbuco", "cut": 10102,
            "provincia": "Llanquihue", "región": "Los Lagos"},
        {"nombre": "Cochamó", "cut": 10103,
            "provincia": "Llanquihue", "región": "Los Lagos"},
        {"nombre": "Fresia", "cut": 10104,
            "provincia": "Llanquihue", "región": "Los Lagos"},
        {"nombre": "Frutillar", "cut": 10105,
            "provincia": "Llanquihue", "región": "Los Lagos"},
        {"nombre": "Los Muermos", "cut": 10106,
            "provincia": "Llanquihue", "región": "Los Lagos"},
        {"nombre": "Llanquihue", "cut": 10107,
            "provincia": "Llanquihue", "región": "Los Lagos"},
        {"nombre": "Maullín", "cut": 10108,
            "provincia": "Llanquihue", "región": "Los Lagos"},
        {"nombre": "Puerto Varas", "cut": 10109,
            "provincia": "Llanquihue", "región": "Los Lagos"},
        {"nombre": "Castro", "cut": 10201,
            "provincia": "Chiloé", "región": "Los Lagos"},
        {"nombre": "Ancud", "cut": 10202,
            "provincia": "Chiloé", "región": "Los Lagos"},
        {"nombre": "Chonchi", "cut": 10203,
            "provincia": "Chiloé", "región": "Los Lagos"},
        {"nombre": "Curaco de Vélez", "cut": 10204,
            "provincia": "Chiloé", "región": "Los Lagos"},
        {"nombre": "Dalcahue", "cut": 10205,
            "provincia": "Chiloé", "región": "Los Lagos"},
        {"nombre": "Puqueldón", "cut": 10206,
            "provincia": "Chiloé", "región": "Los Lagos"},
        {"nombre": "Queilén", "cut": 10207,
            "provincia": "Chiloé", "región": "Los Lagos"},
        {"nombre": "Quellón", "cut": 10208,
            "provincia": "Chiloé", "región": "Los Lagos"},
        {"nombre": "Quemchi", "cut": 10209,
            "provincia": "Chiloé", "región": "Los Lagos"},
        {"nombre": "Quinchao", "cut": 10210,
            "provincia": "Chiloé", "región": "Los Lagos"},
        {"nombre": "Osorno", "cut": 10301,
            "provincia": "Osorno", "región": "Los Lagos"},
        {"nombre": "Puerto Octay", "cut": 10302,
            "provincia": "Osorno", "región": "Los Lagos"},
        {"nombre": "Purranque", "cut": 10303,
            "provincia": "Osorno", "región": "Los Lagos"},
        {"nombre": "Puyehue", "cut": 10304,
            "provincia": "Osorno", "región": "Los Lagos"},
        {"nombre": "Río Negro", "cut": 10305,
            "provincia": "Osorno", "región": "Los Lagos"},
        {"nombre": "San Juan de la Costa", "cut": 10306,
            "provincia": "Osorno", "región": "Los Lagos"},
        {"nombre": "San Pablo", "cut": 10307,
            "provincia": "Osorno", "región": "Los Lagos"},
        {"nombre": "Chaitén", "cut": 10401,
            "provincia": "Palena", "región": "Los Lagos"},
        {"nombre": "Futaleufú", "cut": 10402,
            "provincia": "Palena", "región": "Los Lagos"},
        {"nombre": "Hualaihué", "cut": 10403,
            "provincia": "Palena", "región": "Los Lagos"},
        {"nombre": "Palena", "cut": 10404,
            "provincia": "Palena", "región": "Los Lagos"},
        {"nombre": "Coyhaique", "cut": 11101, "provincia": "Coyhaique",
            "región": "Aysén del Gral. C. Ibáñez del Campo"},
        {"nombre": "Lago Verde", "cut": 11102, "provincia": "Coyhaique",
            "región": "Aysén del Gral. C. Ibáñez del Campo"},
        {"nombre": "Aysén", "cut": 11201, "provincia": "Aysén",
            "región": "Aysén del Gral. C. Ibáñez del Campo"},
        {"nombre": "Cisnes", "cut": 11202, "provincia": "Aysén",
            "región": "Aysén del Gral. C. Ibáñez del Campo"},
        {"nombre": "Guaitecas", "cut": 11203, "provincia": "Aysén",
            "región": "Aysén del Gral. C. Ibáñez del Campo"},
        {"nombre": "Cochrane", "cut": 11301, "provincia": "Capitán Prat",
            "región": "Aysén del Gral. C. Ibáñez del Campo"},
        {"nombre": "O'Higgins", "cut": 11302, "provincia": "Capitán Prat",
            "región": "Aysén del Gral. C. Ibáñez del Campo"},
        {"nombre": "Tortel", "cut": 11303, "provincia": "Capitán Prat",
            "región": "Aysén del Gral. C. Ibáñez del Campo"},
        {"nombre": "Chile Chico", "cut": 11401, "provincia": "General Carrera",
            "región": "Aysén del Gral. C. Ibáñez del Campo"},
        {"nombre": "Río Ibáñez", "cut": 11402, "provincia": "General Carrera",
            "región": "Aysén del Gral. C. Ibáñez del Campo"},
        {"nombre": "Punta Arenas", "cut": 12101, "provincia": "Magallanes",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "Laguna Blanca", "cut": 12102, "provincia": "Magallanes",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "Río Verde", "cut": 12103, "provincia": "Magallanes",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "San Gregorio", "cut": 12104, "provincia": "Magallanes",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "Cabo de Hornos", "cut": 12201, "provincia": "Antártica Chilena",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "Antártica", "cut": 12202, "provincia": "Antártica Chilena",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "Porvenir", "cut": 12301, "provincia": "Tierra del Fuego",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "Primavera", "cut": 12302, "provincia": "Tierra del Fuego",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "Timaukel", "cut": 12303, "provincia": "Tierra del Fuego",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "Natales", "cut": 12401, "provincia": "Última Esperanza",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "Torres del Paine", "cut": 12402, "provincia": "Última Esperanza",
            "región": "Magallanes y Antártica Chilena"},
        {"nombre": "Santiago", "cut": 13101, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Cerrillos", "cut": 13102, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Cerro Navia", "cut": 13103, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Conchalí", "cut": 13104, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "El Bosque", "cut": 13105, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Estación Central", "cut": 13106,
            "provincia": "Santiago", "región": "Metropolitana de Santiago"},
        {"nombre": "Huechuraba", "cut": 13107, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Independencia", "cut": 13108, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "La Cisterna", "cut": 13109, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "La Florida", "cut": 13110, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "La Granja", "cut": 13111, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "La Pintana", "cut": 13112, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "La Reina", "cut": 13113, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Las Condes", "cut": 13114, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Lo Barnechea", "cut": 13115, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Lo Espejo", "cut": 13116, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Lo Prado", "cut": 13117, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Macul", "cut": 13118, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Maipú", "cut": 13119, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Ñuñoa", "cut": 13120, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Pedro Aguirre Cerda", "cut": 13121,
            "provincia": "Santiago", "región": "Metropolitana de Santiago"},
        {"nombre": "Peñalolén", "cut": 13122, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Providencia", "cut": 13123, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Pudahuel", "cut": 13124, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Quilicura", "cut": 13125, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Quinta Normal", "cut": 13126, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Recoleta", "cut": 13127, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Renca", "cut": 13128, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "San Joaquín", "cut": 13129, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "San Miguel", "cut": 13130, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "San Ramón", "cut": 13131, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Vitacura", "cut": 13132, "provincia": "Santiago",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Puente Alto", "cut": 13201, "provincia": "Cordillera",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Pirque", "cut": 13202, "provincia": "Cordillera",
            "región": "Metropolitana de Santiago"},
        {"nombre": "San José de Maipo", "cut": 13203,
            "provincia": "Cordillera", "región": "Metropolitana de Santiago"},
        {"nombre": "Colina", "cut": 13301, "provincia": "Chacabuco",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Lampa", "cut": 13302, "provincia": "Chacabuco",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Til Til", "cut": 13303, "provincia": "Chacabuco",
            "región": "Metropolitana de Santiago"},
        {"nombre": "San Bernardo", "cut": 13401, "provincia": "Maipo",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Buin", "cut": 13402, "provincia": "Maipo",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Calera de Tango", "cut": 13403, "provincia": "Maipo",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Paine", "cut": 13404, "provincia": "Maipo",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Melipilla", "cut": 13501, "provincia": "Melipilla",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Alhué", "cut": 13502, "provincia": "Melipilla",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Curacaví", "cut": 13503, "provincia": "Melipilla",
            "región": "Metropolitana de Santiago"},
        {"nombre": "María Pinto", "cut": 13504, "provincia": "Melipilla",
            "región": "Metropolitana de Santiago"},
        {"nombre": "San Pedro", "cut": 13505, "provincia": "Melipilla",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Talagante", "cut": 13601, "provincia": "Talagante",
            "región": "Metropolitana de Santiago"},
        {"nombre": "El Monte", "cut": 13602, "provincia": "Talagante",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Isla de Maipo", "cut": 13603, "provincia": "Talagante",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Padre Hurtado", "cut": 13604, "provincia": "Talagante",
            "región": "Metropolitana de Santiago"},
        {"nombre": "Peñaflor", "cut": 13605, "provincia": "Talagante",
            "región": "Metropolitana de Santiago"},
    ]
    comunas.sort(key=nombreComuna)
    return comunas


if __name__ == '__main__':
    print(comunasApi())
